### ISSUE TITLE
Any Method to add Load More !

### ISSUE THREAD

**Issue by AlbanBujupaj** [tylergaw/jribbble#14]
### I tried in this way but seems not working property

        var startCount = 2;
        var html = [];
        $.jribbble.setToken('xxxxxx');
        function addItems() {
            
            $.jribbble.users('albanbujupaj').likes({
                per_page: startCount
            }).then(function(likes) {
                

                likes.forEach(function(like) {
                    html.push('<div class="col-md-4 col-sm-6 animated fadeInUp">');
                    html.push('<div class="atvImg">');
                    html.push('<a href="' + like.shot.html_url + '" target="_blank">');
                    html.push('<img src="' + like.shot.images.normal + '">');
                    html.push('<div class="atvImg-layer" data-img=" ' + like.shot.images.normal + ' "></div>');
                    html.push('</div>');
                    html.push('</a></div>');
                });

                $('.shots').html(html.join(''));
            });
        }

        jQuery(document).ready(function($) {
            addItems();
        });

        $(window).scroll(function() {

            if ($(window).scrollTop() + $(window).height() == $(document).height()) {

                //Here I Want to modified variable and append new items
                console.log(startCount + 6);

                addItems();
                
            }
        });

**Comment by tylergaw** [comment]
Hey @AlbanBujupaj. So the Dribbble API allows for setting `per_page` and `page` parameters for each request. You can see docs for that here http://developer.dribbble.com/v1/#pagination

So, you were on the path, just need to tweak things a bit. Instead of using the `per_page` to get more likes, you need to increment the `page` value and make new requests for each page of likes you want.

I put together a demo for you showing this working with a "Load More" button. You'll need to rework it a bit to have it work with scrolling, but the same concepts should apply. http://codepen.io/tylergaw/pen/qaBGqO?editors=1010

I'm going to close this issue since it's not an issue in Jribbble itself. Let me know if this doesn't get it for you.
